name: Main
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Enter the target environment for the deployment
        options:
        - Staging
        - Production

jobs:
  integration:
    permissions:
      contents: read
    uses: ./.github/workflows/integrate-python-app.yml
  delivery:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: [integration]
    uses: ./.github/workflows/deliver-container-image.yml
  deployment:
    permissions:
      packages: read
    needs: [delivery]
    uses: ./.github/workflows/deploy-aws-app-runner.yml
